### ISSUE TITLE
Editor - text appearance

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#196] opened 2014-12-30 13:44 UTC
Page wizard: Turn off the text appearance options to bold text etc. in fields where it’s useless (e.g. Import Media boxes & Tooltips).
By Fay

**Comment by torinfo** [comment] 2015-03-07 10:11
Wouldn't it be easier to add an extra attribute to the xwd to control this?

**Comment by JohnSmith-LT** [comment] 2015-03-09 12:15
Yeah maybe thats' the only way to get correct control... should it be on by default and turned off or off by default and turned on...

**Comment by torinfo** [comment] 2015-03-09 12:44
I would guess it depends a bit on what you encountered.
For backward compatibillity off by default, and on when marked in the XWD seems to be more logical.

**Comment by JohnSmith-LT** [comment] 2015-03-09 12:51
Hmmm, having thought about it it might be best to turn them off when not required... if we have the single line editor off by default then we need to turn it back on in a lot of places, including Page Title...

However for consistency we'd also need to turn the large textarea editor off by default because certain embed code fields (like You Tube page) currently have the large editor turned on when they shouldn't...

So I turn them both off, add fields in the xwd files for those required to be on - that probably is the best way to go for backward compatibility I think... unless you have any concerns about that? I'm not as familiar with the code lately...

**Comment by torinfo** [comment] 2015-03-09 13:28
Let's see:

 - For embed codes you can use the new type *script*, which will show a source (syntax highlighted) editor

- For html, you can use *html*, this will open the editor in source mode, but you will be able to switch to wysiwig mode. That's the difference with *script*

- The flag to show the inline editor (or not) can be checked in toolbox.js, displayDataType, where you just don't push the textinputs_options.

**Comment by torinfo** [comment] 2015-03-11 21:07
John, we have to revert your changes anyway, because now the fields are not not saved. The editor had the callback to save the attribute, and there is no editor anymore, so there is no save action either.

When the inline editor is off, in stead of creating an editable **div** we must create an **<input>**  and attach the proper callback.

See trelle remarks from Ron about editing the fields directly.

**Comment by JohnSmith-LT** [comment] 2015-03-12 00:04
Doh! Not a problem. I will have a think about it a bit further and do things a bit differently as we discussed...

**Comment by ronm123** [comment] 2015-03-12 11:31
Hi John/Tom is this a related issue... I just tested the QR code page and after adding a URL and playing/saving it seems the URL get's stripped and/or doesn't save in the first place.

**Comment by JohnSmith-LT** [comment] 2015-03-12 11:42
Hi Ron,

Is this a new setup from the Github repository or from a release zip from xerte.org.uk ?

Regards,

John Smith | Learning Technologist
Room A250, Govan Mbeki Building | School of Health & Life Sciences | Glasgow Caledonian University
Cowcaddens Road | Glasgow | G4 0BA

Please address ALL support requests to hlsblt@gcu.ac.uk where one of the School Learning Technologists will pick up the job. This will ensure that all jobs are completed as promptly as possible.
________________________________________

**Comment by ronm123** [comment] 2015-03-12 11:53
Hi John

updated from github yesterday.

Ron

**Comment by JohnSmith-LT** [comment] 2015-03-12 11:59
Yes then it's related. I turned the inline editor off for certain types of fields but never maintained the callback that stored the data. Tom has reverted the changes as we are going to do this differently now so you should pull down the editor/js files which would be the only ones changed...

Regards,

John Smith | Learning Technologist
Room A250, Govan Mbeki Building | School of Health & Life Sciences | Glasgow Caledonian University
Cowcaddens Road | Glasgow | G4 0BA

Please address ALL support requests to hlsblt@gcu.ac.uk where one of the School Learning Technologists will pick up the job. This will ensure that all jobs are completed as promptly as possible.
________________________________________

**Comment by ronm123** [comment] 2015-03-12 12:21
Hi John
have those changes definitely been reverted in develop?
Ron

**Comment by JohnSmith-LT** [comment] 2015-03-12 12:56
Hi Ron,

Tom emailed me last night about reverting the code changes because of the bug which I assumed he had done. Temporarily I have changed a return value to make editor always on again until I can get time to fix. I've committed that change.

Can you let me know if that solves your issue for now?

Regards,

John Smith | Learning Technologist
Room A250, Govan Mbeki Building | School of Health & Life Sciences | Glasgow Caledonian University
Cowcaddens Road | Glasgow | G4 0BA

Please address ALL support requests to hlsblt@gcu.ac.uk where one of the School Learning Technologists will pick up the job. This will ensure that all jobs are completed as promptly as possible.
________________________________________

**Comment by ronm123** [comment] 2015-03-12 13:24
Hi John
that change resolves the issue around being able to add and save a URL using the QR code page so that works now.
It also allows url's to be added and saved in the optional help file and stylesheet fields and an image file field with the graphics and sound page, but whether wrapped between single apostrophes or not neither of those links work. I guess that's a different but not completely un-related issue.

**Comment by JohnSmith-LT** [comment] 2015-03-12 13:30
Thanks Ron, yeah not sure if that feature has ever worked or been tested in the new editor. Tom would know better but i'll open an issue just now so that we don't overlook it...
John

**Comment by torinfo** [comment] 2015-03-12 21:51
Sorry John. I meant we should revert., I didn't do that.

Looking into this particular matter further, it is caused by the editor as well, because it escapes the ' (to &quot);

If I edit the xml by hand and put the 'back, it works.

So.....

 - Add a feature to the xwd to mark entries as pure text and not html, for instance by adding **nohtml** or **nowysiwig** or **wyswyg=false** attributes 

- Implement this by having an ordinary &lt;input type="text"&gt; input box, and that should work

- I personally think that additionally we should change the enginge (xenith.js) to accept an ordinary url as well, and not require the quotes.

I'll have a go this weekend.

**Closed** 2015-03-13 19:05 UTC
