### ISSUE TITLE
Outlook preview link issue

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1066] opened 2022-01-06 10:13 UTC
When adding links to emails in Outlook you sometimes get a preview box for the link:

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/8926470/148366397-620200ea-af10-4cb7-997b-61cbbeaa1892.png)

This includes the text 'Learning Object Title. Overview for the content below' rather than any real text from the project itself. Ideally this should be customisable in the same way as you can now edit the content of twitter card previews (@ronm123).

**Comment by ronm123** [comment] 2022-01-06 12:00
@FayCross I can't reproduce this and don't ever see a preview when adding a link to an email. I tested the link from your example too and don't see that preview. I wondered if perhaps this was with Outlook online rather than local but quickly tested there too and don't see this. Could it be some kind of proxy server caching or something else at Nottingham picking up that preview? Do you get the same with external Xerte links? If I view and inspect your example I don't see anything that matches that text you are seeing e.g. Learning Object Title. Overview Title for the content below so I'm not sure where that is coming from or why/how the preview is being created?

**Comment by FayCross** [comment] 2022-01-06 13:27
@ronm123 The previews are apparently on by default ([Link previews](https://support.microsoft.com/en-us/office/use-link-preview-in-outlook-com-and-outlook-on-the-web-ebbfd8ce-d38e-40ef-bb8c-a5362e881163)) but in my experience they don't work consistently for all links you add. I get one for https://xot.xerte.org.uk but not if I link to a project from there - I'll play around and see if I can recreate with one outside UoN.

That text isn't coming from the project data but from [rloObject.htm](https://github.com/thexerteproject/xerteonlinetoolkits/blob/86bdc28e2aaae1fbf8b28c2c9e1a2753f45c2f9f/modules/site/player_html5/rloObject.htm)

**Comment by ronm123** [comment] 2022-01-06 14:24
@FayCross so according to that [Link previews page](https://support.microsoft.com/en-us/office/use-link-preview-in-outlook-com-and-outlook-on-the-web-ebbfd8ce-d38e-40ef-bb8c-a5362e881163) on the support site this does only work on Outlook.com and Outlook on the web and not local Outlook? That said I checked in my online Outlook and the option is on but I still don't get previews.

I can see the place holder text in the site player but we don't have the same place holder text in the xot player. What happens when you add a link to an xot project?

Rather than an optional property perhaps the placeholder text should be automatically replaced with the LO title and page title? e.g. change:

id="pageTitle">Learning Object Title<
id="pageSubTitle">Overview title for the content below<
to:
id="pageTitle">%LOTITLE%<
id="pageSubTitle">%LOSUBTITLE%<

and then use replace in play.php?

**Comment by FayCross** [comment] 2022-01-06 15:02
Good idea - I'll give that a go. None of the XOT projects I've tried seem to show the preview

**Closed** 2022-03-04 18:22 UTC
Labels: bug, enhancement
