### ISSUE TITLE
Improve naming of export zips

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#466] opened 2016-04-27 14:16 UTC
From Community Wish List

Append the text 'deployment' or 'archive' to the zips created when you export a project

**Comment by JohnSmith-LT** [comment] 2016-05-12 10:30
Hi Fay,

I've added this temporarily to the Decision Tree to let people see if this is what is desired.

However, regarding the XOT template, we have deployment, archive, offline, scorm (1.2 and 2004) and would we also want to add flash / html5 to the name? Or we assume HTML5 and only add Flash since that would be a special case?

So we'd possibly have "Project_Name_deployment_flash.zip" or "Project_Name_archive.zip"

**Comment by FayCross** [comment] 2016-05-12 10:41
Hmm, I never export so not sure what would be best. I don't think it would need to say html5 on them all. I take it none of this would affect importing something back in?

**Comment by JohnSmith-LT** [comment] 2016-05-12 10:48
No it's just the filename that is prompted when you hit one of the export options.

I assume it came up as it's possible to overwrite say and archive one with a scorm one that has been saved for a different option...

I'll wait to see what other people think before implementing the rest but yeah as you say adding _html5 to the filename is probably pointless since it's the norm and I would just add _flash possibly if that option is chosen.

**Comment by ronm123** [comment] 2016-05-12 11:00
Hi both
I usually manually rename the zip when I export to reflect the type I chose. I guess it's useful to automatically add the format chosen but we need to make sure this doesn't break anything else e.g. export links in the syndication feed, .htaccess rules etc? Not saying that it will but I know for instance syndicate.php include links that end with /export_1123 and /scorm_123

**Comment by JohnSmith-LT** [comment] 2016-05-12 11:08
Hi Ron,

The change I made only changes the name that is presented to the user for saving, similar to if the user manually added the suffix in the project name so i'm pretty sure it won't break anything that the user couldn't break by renaming.

I assume that /export_1123 and /scorm_123 simply redirect to the relevant export.php? page with the correct parameters? It would definitely be useful to test this though before deployment.

**Comment by ronm123** [comment] 2016-05-12 11:37
Hi John
I just quickly checked your commit on a live install and seems to work fine in that the syndication feed link still works so isn't affected by he appending of archive etc.
However seems perhaps there's a separate issue with the syndication feed code displaying links that aren't really relevant. e.g. Create a decision tree project, make it part of the export feed, view the export feed and you get two links e.g.
Download this content from installaddress/website_code/php/scorm/export.php?scorm=false&template_id=123
Download this as a scorm package from installaddress/website_code/php/scorm/export.php?scorm=true&template_id=123

Both links do actually create a zip but obviously there is no scorm export at the moment from decision tree and using either link results in filename_deployment.zip

**Comment by JohnSmith-LT** [comment] 2016-05-12 11:52
Ok, i'll take a look at that. I suspect that has always been the case for decision tree as there is a lot less code and error checking in there than in the XOT one.

Just to be sure, what should each of the two urls above give? Or is it that fact that you get one url in the feed that says scorm=true that is the issue? I assume that the two URLs presented (if indeed you should be getting 2 for this template) should still be Archive and Deployment?

**Comment by ronm123** [comment] 2016-05-12 12:14
Hi John
I'm not sure this is a major issue as you say it's likely always been the case.
I'm not sure how much the syndication feed is used but I've always thought that should show the same export options as is available for any given template if that template has been added to the feed of course. Obviously because SCORM export isn't currently available for decision anyway it just downloads a deployment zip regardless of the link used.
More importantly what I've shown users how to do is to add a download link with in their LO's by adding a project to the syndication feed, enabling for export, copying the link from the syndication feed and then adding that link to a page in the resource. The syndication feed only currently shows links for scorm=false and scorm=true regardless of template used. Yet given that we have offline export in the xot template that might be more likely the link users would want or to add to their LO's for learners to download for offline access. I'm not sure if there's a way to manually construct and add a link to achieve that. If we were to add extra links or remove redundant links to the syndication feed to reflect the export options available for a given template I'm not sure the archive option should be include because that's a bit redundant these days e.g. you can't really edit the rlt file in xerte desktop any longer because of the mismatch in templates and html 5 output.

**Comment by JohnSmith-LT** [comment] 2016-05-16 13:12
Haven't yet addressed the syndication feed problems yet since I can't reproduce... All I see when I follow your steps above in Mac/Chrome is:

![image](https://cloud.githubusercontent.com/assets/3907362/15290405/28b959d8-1b70-11e6-82c8-686a2d804509.png)

**Comment by ronm123** [comment] 2016-05-16 16:21
Hi John
is that the standard rss feed or the syndication feed? If the latter you need to make those projects part of the export feed e.g.
![image](https://cloud.githubusercontent.com/assets/5167146/15295861/9d5ba9b6-1b8a-11e6-9729-7c107c001e2b.png)

**Comment by JohnSmith-LT** [comment] 2016-05-18 09:13
Hi Ron,

Sorry for delay getting back to you. I have these ticked in all projects:

![image](https://cloud.githubusercontent.com/assets/3907362/15353340/77367dcc-1ce0-11e6-9842-dd55711ffb9c.png)

And yet I still get this in Chrome:

![image](https://cloud.githubusercontent.com/assets/3907362/15353430/edf54308-1ce0-11e6-87ad-ac019d235377.png)
![image](https://cloud.githubusercontent.com/assets/3907362/15353414/d612e9de-1ce0-11e6-936b-31f4a0f8bc2a.png)

And this in Firefox:

![image](https://cloud.githubusercontent.com/assets/3907362/15353379/aaeaeaea-1ce0-11e6-87ea-c0065d55e84f.png)
![image](https://cloud.githubusercontent.com/assets/3907362/15353394/bc480174-1ce0-11e6-98d6-98d29449ea31.png)

Is this a bug? This is a new install checked out of Github develop rather than v3.2 but if there are errors in develop they could make their way into v3.3 when the time comes...

**Comment by ronm123** [comment] 2016-05-18 10:59
Hi John
sorry this likes too basic a question so perhaps there is a bug with different revisions but just to be sure...
The plain rss feed never shows the export links but for the export links to show in the syndication feed the include in export feed needs to be ticked as yes via RSS properties.
That actually is all that is needed for a self-access export link to work but for most users to get the format of that it's easiest to grab from the syndication feed.
For the projects and their export links to show in the syndication feed the include in syndication feed needs to be ticked in the open content properties:
![image](https://cloud.githubusercontent.com/assets/5167146/15356281/c92dc7ac-1cef-11e6-98e9-ced73e422578.png)

Now I suspect you already have this so could it be caching? Seems unlikely to be a revision difference but could be I guess?

**Comment by JohnSmith-LT** [comment] 2016-05-18 11:03
Ah, thanks Ron,

That was the missing key, I hadn't ticked that box. I'll take a look at that issue now that I can reproduce.

**Comment by JohnSmith-LT** [comment] 2016-05-18 11:18
I'm going to close this and open a new one to have the syndicate.php page and export.php pages modified as we have issues with scorm download links for RSS and Decision Tree and you can even download an RSS template as a Scorm package.

**Closed by JohnSmith-LT** 2016-05-18 11:18 UTC
Labels: enhancement
