### ISSUE TITLE
Twitter card code in Bootstrap bugs

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1067] opened 2022-01-07 10:20 UTC
The new twitter card code is breaking Bootstrap projects. Themes no longer load correctly and %TWITTERCARD% can be seen at the top of the project so isn't being replaced with the meta tag correctly. This happens even when the twitter card optional property isn't added

**Comment by ronm123** [comment] 2022-01-07 10:37
@FayCross are you testing this via a local develop install? I can't reproduce via my local develop with various existing and new Bootstrap projects with and without the optional Twitter card property added. Could it be caching? @torinfo do you see this problem?

**Comment by FayCross** [comment] 2022-01-07 10:41
It's definitely not a caching issue. I can see on https://xot310beta.dlearning.nl/ as well as local xampp. After another look it's only an issue in preview & not play

**Comment by ronm123** [comment] 2022-01-07 11:04
@FayCross ok so I've just added the same code from play.php to preview.php if you pull that down does that fix it for you?
I'm wondering why the same issue doesn't happen with xot project preview because the code isn't in there either. @torinfo do I need to add the %TWITTERCARD% replace code to xerte/preview.php too?

**Comment by FayCross** [comment] 2022-01-07 11:12
@ronm123 yes that's working now. Thanks

**Comment by FayCross** [comment] 2022-01-07 17:12
@ronm123 I looked at this quickly earlier too as I didn't know why it was working in XOT. It looks like preview.php loads play.php which is different to the way it works in the Bootstrap template.

**Comment by torinfo** [comment] 2022-01-08 19:48
@FayCross @ronm123 Yes, xot preview just includes play.php. Probably a good idea to do the same for site and decision. I don't know why that is not done. I'll verify and if theresis no reason to keep them separately, I'll make that change because it definitely makes maintenance easier.

**Comment by ronm123** [comment] 2022-06-30 17:27
@FayCross @torinfo @JohnSmith-LT I've just been trying to quickly look at why this isn't working in Bootstrap. Looking at this previous issue discussion suggests it was working in Bootstrap on 7th Jan when Fay raised the issue and I added code to preview.php too. However it's not working now and I can't see why. The code seems to be in the site play.php and rloobject and I'm seeing the twittercard metadata when viewing a bootstrap via preview.php but not via play.php.

**Comment by JohnSmith-LT** [comment] 2022-06-30 17:35
I’ve committed a fix… it wasn’t me as far as I can tell but only in play.php for bootstrap:

$tcoption = $xml->getLOAttribute('tcsite');

There’s then a check for $tcoption ==”true” which it never is since tcsite is a url…

Regards

John

**Comment by JohnSmith-LT** [comment] 2022-06-30 17:39
It was you two months ago @ronm123 ;-)

![image](https://user-images.githubusercontent.com/3907362/176742266-02453cdb-e495-4767-ba56-e8e345ed3a94.png)

**Comment by ronm123** [comment] 2022-06-30 18:04
@JohnSmith-LT oh dear! :-(  Very strange given it was correct in preview.php but glad you found it!
@torinfo sorry can you replace site play.php on xot.xerte.org.uk with the updated file or just make the same quick change?
I want to validate the card and then probably change the image used to fit the card.

**Closed** 2023-05-03 09:29 UTC
Labels: bug, Bootstrap template
