### ISSUE TITLE
track/display page visit in TOC

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#587] opened 2017-02-28 14:37 UTC
I think this has been discussed before and certainly requested during training sessions and it's likely to be requested by others given that other popular tools have this now and that is to show some indication of pages already visited by a learner. It's especially relevant where the navigation is set to non-linear or where there are page links within content going to other pages. e.g. a learner views the page types example and when viewing the TOC they see an indication of which pages they've visited:
![image](https://cloud.githubusercontent.com/assets/5167146/23409307/04cebac8-fdc3-11e6-8f29-7686eb62f42e.png)

Could also be part of a visual progress indicator too e.g.
![image](https://cloud.githubusercontent.com/assets/5167146/23409378/49f22de2-fdc3-11e6-8b47-23df22d6d671.png)

and would be useful in all of the project templates

**Comment by JohnSmith-LT** [comment] 2017-03-01 12:35
Hi @ronm123 

If you update now and enable purple theme then the ticks should be showing in the menu. If you have a better tick icon then please feel free to upload instead of the one that i've uploaded to test this.

John

**Comment by ronm123** [comment] 2017-03-01 12:51
Hi @JohnSmith-LT had to clear cache but works great! The icon looks fine but wonder if a Font Awesome icon would work and thefeore inherit theme colours or be more easily controlled rather than having to create coloured icons for each theme? e.g. `<i class="fa fa-check-circle" aria-hidden="true"></i>`
Cheers
Ron

**Comment by torinfo** [comment] 2017-03-01 12:51
Hi @ronm123, @JohnSmith-LT ,

If we base the marks on the information of the tracking code, we can (under circumstances) keep track of this information between sessions.

**Comment by JohnSmith-LT** [comment] 2017-03-01 12:55
That would be very interesting to do...

It would only (as far as I can see) mean updating the single function in menu.html to look at the tracking code instead of the .built flag...

**Comment by JohnSmith-LT** [comment] 2017-03-01 13:10
Have changed it now to font-awesome @ronm123 and seems to work ok...

**Comment by torinfo** [comment] 2017-03-01 13:12
I will have a look at that (I probably need to add fnctionality to the tracking code).

**Comment by JohnSmith-LT** [comment] 2017-03-01 13:21
Cheers Tom

**Comment by ronm123** [comment] 2017-03-01 13:26
@torinfo how does that tracking code get stored and retrieved between sessions? localStorage or only when exported/imported as SCORM?

Often wondered about the functionality to resume with LO's viewed directly from Xerte. e.g. SL content prompts to resume or restart even when just viewed from a web link and I know we have the enable resuming to bookmark particular page or send direct links to a particular page but enabling a learner to resume where they left off even when viewing a link or embedded from Xerte would be a popular enhancement.

@JohnSmith-LT FA Icon works great!

**Comment by ronm123** [comment] 2017-03-01 13:38
@JohnSmith-LT I just tested this with other themes and because the updated css doesn't exist in the other themes the icon is butting up agaianst the last letter of the page titles e.g.
![image](https://cloud.githubusercontent.com/assets/5167146/23461930/c3431664-fe83-11e6-9bb3-77c56ed1ade3.png)

Perhaps a quick n dirty fix for that is just adding a space in the append code e.g.
`$thisItem.append(' <i class="fa fa-check-circle" aria-hidden="true"></i>');`
Which then displays as:
![image](https://cloud.githubusercontent.com/assets/5167146/23461989/ff1f2b82-fe83-11e6-95fd-adbae802d35f.png)

I know it's also possible to add css to do this better via that same append etc but I guess that moves away from Tom's idea of removing styles from the model files so a quick fix rather than adding the css to all the themes might be just to include that space?

**Comment by torinfo** [comment] 2017-03-01 14:13
@ronm123 

For now it's indeed just for SCORM sessions. Later it will be available for xAPI as well.

**Comment by ronm123** [comment] 2017-03-01 21:30
@JohnSmith-LT only just noticed that with the purple theme if I close the LO and re-open it correctly clears all the ticks but with all the other themes it's showing the ticks on all pages all the time even if I haven't viewed that LO before e.g. create a new LO, default theme, add a few pages, play, view the toc, all pages ticked. I guess that's because none of the other themes have the #menuItems styles.
Do we need to go through and add all the #menuItems styles to all the other themes or is there a better way to fix that?

**Comment by JohnSmith-LT** [comment] 2017-03-02 09:41
Hi @ronm123 give the latest update a try when you get time. I've flipped the logic oin the menu to use a notvisited flag by default and have stripped the css back out of the purple theme. If we want to float the tick to the right then we can add some css to the master layout.

**Comment by ronm123** [comment] 2017-03-02 10:14
Hi @JohnSmith-LT yes that works on all themes now. It did look better floated right and I guess we don't have too many themes to add the css to each if thats the better way to do it?
Cheers
Ron

**Comment by ronm123** [comment] 2017-03-02 11:17
@JohnSmith-LT @torinfo is there already a variable that holds the total number of pages viewed or not viewed? e.g. part of the builtPage functionality or page tracking?
Wondering about displaying a progress bar instead of the page x of y
so something like pages viewed * total pages /100 and move the progress bar accordingly

**Comment by JohnSmith-LT** [comment] 2017-03-02 11:51
No variable but this should give you the count of those built

$(x_pageInfo).filter(function(){return this.built !== false;}).length

**Comment by ronm123** [comment] 2017-03-02 16:09
Cheer @JohnSmith-LT that works and I'm just experimenting at the moment with what I can get working just via a themes .js file. Here's an example of two things:
a
1) hiding/showing some of the footer buttons via a toggle
2) displaying a progress bar rather than page x of y
http://training.mitchellmedia.co.uk/xot/play.php?template_id=279 

At the moment though the progress bar is only changing on click of the next and prev buttons. Is there a way I can pick up on page change from the theme's js file rather than onclick of the nav buttons?

**Comment by JohnSmith-LT** [comment] 2017-03-02 20:18
Hi @ronm123, that looks pretty cool but yes I can see the problem that you face since the button clicks happen before the .built is set so they are always 1 step behind...

I always planned to introduce event dispatching to xenith but haven't got around to it - it would allow you to hook your js into a beforePageLoad and afterPageLoad event, or similar, and have code executed when you wish...

In the meantime though, every page model calls x_pageLoaded() as the last thing on the page when the model loads and finishes initialising so at a push you can intercept that and then have your code execute straight afterwards (jumping in front of it could give a similar effect to what you are seeing now - 1 step behind...

I looked at your code and you could do something like this:

```
var	x_PL = x_pageLoaded,
	x_pageLoaded = function() {
  		x_PL();
  		doPercentage();
    },
    doPercentage = function () {
		var totalpages=x_pageInfo.length;
		var pagesviewed=$(x_pageInfo).filter(function(){return this.built !== false;}).length;
		var progress=Math.round((pagesviewed*100)/totalpages);
		$(".css").css({"width": progress+"%"});
		$('.percentageTxt').html(progress+"% COMPLETE");
    };
doPercentage();
```

Now it's not very elegant but it appears to work in my tests but you'd have to test to see if it works as intended in your situation...

To explain what it does:

- First it gets a reference to the original x_pageLoaded() function so that you can overwrite it but still execute the original code...
- Next it creates a NEW x_pageLoaded() function which calls the old one (via the reference) then calls your new function straight afterwards.
- Lastly it declares your new function and then executes it afterwards (since x_pageLoaded() may have already been called on the first page before our code executes and calling it multiple times is fine...

I don't think you need that &nbsp; either in the div as it should work fine without it and could give a flash of the size you are seeing just now while waiting for a button click...

**Comment by ronm123** [comment] 2017-03-03 09:31
Cheers @JohnSmith-LT that's great! Thanks for the explanation too. 
Yeah originally I had the percentage text in the bar but after moving the text out and making the bar thinner I realised it didn't work without something in the div hence the & nbsp;
I tweaked some of the ID and class names and set the relevant styles in the js file so that this can be added to any theme or the script panel of any LO. I updated my online example which works great. There's a bit more I want to add re moving buttons around but I think I can sort that.
Cheers
Ron

**Comment by JohnSmith-LT** [comment] 2017-03-03 09:49
I think if you set the div css display option to 

display: block;

then it may work. I know I have a div in some other page doing similar which has no space in it and it works but i'm setting the px size rather than % so not sure if that is also interfering...

**Comment by FayCross** [comment] 2017-03-31 10:20
@ronm123 I've just noticed that the css for the progress bar is all in xenith.js - is it ok for me to move it to one of the stylesheets?

Also - I'm closing this as I think it's all been done. Reopen it if I'm wrong

**Closed by FayCross** 2017-03-31 10:20 UTC
Labels: Bootstrap template, enhancement, New feature, XOT template

**Comment by ronm123** [comment] 2017-03-31 10:40
@FayCross do you mean the progress bar or the TOC ticks?
I don't have time to look right now but can check later or next week. I didn wonder about adding an optional property for users to control the colour of the progress indicator and I guess the same could be useful for the ticks in the TOC too.
