### ISSUE TITLE
Progress bar % calculated incorrectly on projects with menu

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#621] opened 2017-04-21 08:56 UTC
In projects were navigation is set to menu, the progress bar considers the menu page that you initially view as one of the pages to 'complete'.

e.g. in a project of 4 pages the progress bar already says 20% complete when you are viewing the initial menu page. I think this would be better to say 0% until you view proper pages.

**Comment by JohnSmith-LT** [comment] 2017-05-25 11:37
I’ve not closed this yet as i've not taken menu connector into consideration yet is this desirable too?

What do you think @ronm123

**Comment by ronm123** [comment] 2017-05-25 13:32
@JohnSmith-LT If I understand your question correctly do you mean should we exclude viewing a menu connector page from being counted as part of progress bar? If so I'd say No. I think menu connector pages should be included as part of the progress bar percentage. TBH I'm not even sure I agree with @FayCross ;-) that the the first page when set to menu navigation should show 0%. In reality if you only had a project with 4 pages would you turn on the progress bar? If there are more pages then the percentage for that first view will be much lower but could still be a page with info to read or an image to view etc and is not really much different to whatever the first page is with linear navigation selected in that it's still part of the total number of pages. I can see there is a subtle difference in that it's not a page that's manually added but I think the issue is exaggerated when there is only 4 pages compared with a larger number. But if you've changed the code to exclude that 1st menu navigation page now that's fine by me too. But certainly in terms of the menu connector page or any of the connector pages I would want them counted as part of the pages viewed and progress bar percentage. 

I think a bigger consideration now is whether we need to also have an option to link the 'track completion' code for the results page with the progress bar functionality. But that's a more complicated discussion I think.

**Comment by JohnSmith-LT** [comment] 2017-06-01 12:06
It's not set in stone - we can revert it if it isn't really an issue as you suggest and detracts from the user experience...

**Closed** 2017-06-07 09:04 UTC
Labels: bug, XOT template
