### ISSUE TITLE
Iframe not working inside tabs in Tabbed Navigator+

### ISSUE THREAD

**Issue by obgeneralao** [thexerteproject/xerteonlinetoolkits#778] opened 2018-06-16 14:09 UTC
Hi,

I included a PHET simulation inside the tabs of **Tabbed Navigator+** and the said simulation would not load. However the same simulation (as an iframe) works properly in **Plain Text**. The weird thing is when I click on the next  button (to move away from **Tabbed Navigator+**) to proceed to the next page and then go back to the said simulation either by clicking on **Back** button or clicking on the **Contents** button then the said simulation would now load.

Thanks for being accomodating.

**Comment by JohnSmith-LT** [comment] 2018-12-02 12:42
Hi Oliver,

I've tried reproducing this problem using iframes in various Tab+ pages and can't reproduce. I have only been using YouTube iframes though and it may be specific to your particular code so are you able to provide a link to a LO that isn't working for you and/or the actual iframe code that you are using? Could it be that the contents are taking a while to load which is why moving and going back works?

Let me know and i'll take another look.

John

**Comment by JohnSmith-LT** [comment] 2019-11-17 18:17
Hi @obgeneralao 

I never got a reply to the above, not sure if you just didn't see it because I didn't use your name handle. Anyway, I still can't reproduce so I am going to close it but if it is still an issue then please re-open and let me know and possibly supply some iFrame code that doesn't work for you or a link to a public LO that is showing the bug in action.

Kind regards,

@JohnSmith-LT

**Closed by JohnSmith-LT** 2019-11-17 18:17 UTC
Labels: Needs testing, bug
