### ISSUE TITLE
Problems with Example Page Types (spreadsheet)

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#1125] opened 2022-06-23 15:42 UTC
Hi @ronm123 

Just working through this worksheet and cannot find the issue with Interactive Text (nor the reference to top, left, or right). Is it the correct page you are referencing because the page text shows fine for me:

![image](https://user-images.githubusercontent.com/3907362/175339549-ec57e896-bee0-4350-a6bc-50e323b91b17.png)

![image](https://user-images.githubusercontent.com/3907362/175339632-94c2b3c0-0ed6-457c-b2ab-3c00bcb53f20.png)

**Comment by JohnSmith-LT** [comment] 2022-06-23 15:48
Have also tested Dictation and with no optional settings selected it seems to work for me:

![image](https://user-images.githubusercontent.com/3907362/175340788-6d26e5f4-b00e-42e3-b9ee-8ef9821e428a.png)

Do you have non-working examples of each of these that you can share so that I can test further?

**Comment by torinfo** [comment] 2022-06-23 16:09
@JohnSmith-LT I think we figured out that dictation doesn't work if you use the media file on the highest level,  with the accompanying transcript.xml file (just like in the page demonstrator).

That issue was fixed by me (also caused by me). I changed .htaccess files such that (at least on appropriately configured apache servers) xml are not served directly anymore.

The fix is to allow xml files in the media folder.

**Comment by ronm123** [comment] 2022-06-28 10:48
@JohnSmith-LT @torinfo sorry I can't find this issue with interactive text now. As you say perhaps I added that issue under the wrong page but I can't find what page I might have been referring to :-( I do recall changing the layout option in whatever page I was testing and it not making a difference and I'm wondering if it was Sortable grid which does have Left, Right and Top options and in fact testing that now I can an error viewing that page in the editor. e.g. I don't see any page text box:
![image](https://user-images.githubusercontent.com/5167146/176160545-1e2e7099-b820-4703-8cb3-e863fb5c8676.png)

and also in the console I get numerous errors but I suspect are related to the codesnippet commit that @torinfo has added so may occur on other page too:
Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "codesnippet" was not found at...
In fact that is the cause and happens on lots of pages so is a separate issue.

**Comment by JohnSmith-LT** [comment] 2022-06-28 10:57
Hi @ronm123 Yeah that's fine, I just thought i'd look at some of those issues and couldn't located that one... I'll close this now and we can re-open if it rears it's head again or we figure out what page it should have been...

**Comment by ronm123** [comment] 2022-06-28 11:24
@JohnSmith-LT found it - sortable grid. But with a new sortable grid page it's fine. I was using a page types demonstrator and I'm guessing @FayCross created the original demo of this page containing chemical elements.
In my existing page there is no option for Grid Size e.g. Small, Medium, Large Full and I'm guessing it's defaulting to full and so not showing the page text. 
![image](https://user-images.githubusercontent.com/5167146/176166847-0d1e64ed-c123-4fe5-b7c7-6673887f7e39.png)

If I create a new sortable grid page the grid size option is there and defaults to medium so the page text appears and still appears when set to small or large but not when set to full which is correct and common with other pages too.
![image](https://user-images.githubusercontent.com/5167146/176167053-c52592df-042b-44a7-a142-b39ee5b47764.png)
Not sure when the change was made but perhaps is quite old and only impacts older projects so will close the issue again.

**Comment by FayCross** [comment] 2022-06-29 17:59
@ronm123 I've just looked and the grid size option was only added to the xwd in May this year - so not long enough ago for us to ignore!

**Comment by FayCross** [comment] 2022-06-29 19:58
I

**Closed by FayCross** 2022-06-29 19:58 UTC
