### ISSUE TITLE
Editor - right click options

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#181] opened 2014-12-28 12:49 UTC
Page wizard: Right click options (Copy, Cut, Paste). Remove these options if most people’s browser settings are going to stop these working.
By Fay

**Comment by torinfo** [comment] 2015-03-13 19:08
I agree, but I don't know (yet) how to switch them off.

**Comment by torinfo** [comment] 2015-03-14 16:07
Duplicate of #209

**Closed by torinfo** 2015-03-14 16:07 UTC
