### ISSUE TITLE
Glossary bug

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1099] opened 2022-05-18 12:54 UTC
In develop, if a glossary word appears in a normal link's href then it tries to turn it into a glossary hover link and causes the HTML tags to show on screen as text ([example of bug](https://xot310beta.dlearning.nl/play.php?template_id=67#page1)). In previous versions, the glossary word was ignored in tag attributes so worked as expected only on normal text ([example of this working](https://xot.xerte.org.uk/play_325#page1))

I these examples, the word xerte is in the glossary and the links are to https://xerte.nottingham.ac.uk
@JohnSmith-LT I think this is likely to be related to the changes you've recently done

**Comment by JohnSmith-LT** [comment] 2022-05-23 11:36
Hi @FayCross I think I've fixed this by letting the browser create a document fragment from the section and then traversing the DOM tree and only looking at text nodes. If you are happy that this is working then please close the issue although...

...as a consequence of all this glossary work there are now a couple of flags in use to "ignore whitespace" and also replace "multiple terms" that are the same:

![image](https://user-images.githubusercontent.com/3907362/169810506-7a05eaf5-5039-4e7f-8364-f7cd519948aa.png)

The default combination (shown in image) should have same effect as before but do you think it would be useful to expose one or both of these as optional LO properties (probably in a group with the glossary) or as optional page properties?

**Comment by FayCross** [comment] 2022-06-08 11:00
@JohnSmith-LT I was testing the download results page changes in different browsers and have found that this line in the glossary code is stopping any projects opening in IE (it doesn't like =>)

line 4501:
`tempText = nodes.length === 1 ? nodes[0].textContent : Array.from(fragment.childNodes).map(x => x.outerHTML).join('');`

We spoke about whether we still support IE in last dev meeting but don't think we came to any conclusion!

**Comment by FayCross** [comment] 2022-06-08 13:44
@JohnSmith-LT that works, thanks. I've tested the glossary fix too where it was breaking if link URLs included a glossary word and that works now too.

One thing that I don't know whether it's really a problem though. Previously you could have the link text include a glossary word like this: [example 1](https://xerte.nottingham.ac.uk/play_41054#page1) but now it won't pick up on that:  [example 2](https://xot310beta.dlearning.nl/play.php?template_id=67#page1). I think I prefer it not having glossary links within normal links so perhaps that's better anyway (this issue was why I thought of this: https://github.com/thexerteproject/xerteonlinetoolkits/issues/956)

**Comment by JohnSmith-LT** [comment] 2022-06-08 14:41
Yeah that is probably a side effect of the conditional in the nodes parser and could probably be changed if it was an issue further down the line but I think that was more quirky than useful and I'm happy to leave that as it is now since it's probably better to be clear what something does rather than having it multi-layered like this...

**Comment by torinfo** [comment] 2022-07-09 20:47
@JohnSmith-LT The changes to the glossary in 3.11 broke some previous LO's 

For now I've reverted all changes back (because reverting #1099 only didn't work either).

I've put two examples in xot310beta, so that there is some LO that we can test against. We need to add you to that install so you can export from there into your own install.

ERIC Basic (id=100)
Privacy (id=101)

**Comment by JohnSmith-LT** [comment] 2022-07-18 01:29
Hi @torinfo I got the login details from inge but the two projects aren't shared and they are not public - can you share so I can properly check them?

I did manage to get access to the xml though ;-) and I checked them both before pulling down your reverts and after and all Glossary terms seemed to work fine for me although I probably just didn't test the correct thing - can you elaborate more on what exactly was broken with them? I'm curious to know why reverting #1099 didn't work since both @FayCross and myself tested with existing LO's we both have to make sure all was working?!?

I'm also not really sure why your reverts (back to v3.10) don't show the problem that this issue was created to solve - i.e. this example https://xot310beta.dlearning.nl/play.php?template_id=67#page1 should have the link broken but does seem to work?!?

I think between v3.10 and v3.11 we made 3x changes to Glossary (2 of which now don't work):

Escape key closes an open glossary tip (no longer working - this was for accessibility)
Multiple spaces ignored (no longer working as demonstrated by https://xot310beta.dlearning.nl/play.php?template_id=67#page3 and https://xot310beta.dlearning.nl/play.php?template_id=67#page4)
This issue - glossary term appearing in url breaks the html - curiously though this isn't an issue now in https://xot310beta.dlearning.nl/play.php?template_id=67#page1

**Comment by torinfo** [comment] 2022-07-18 10:04
@JohnSmith-LT I share both with you. I'll create an install with your original code, and will point out what goes wrong. Would be good to get all the things back working. I do not revert things lightly but I could not figure out quickly how to get the LO's working again. complete blocks of texts dissapear. Let me set up that install, and I'll be able to pinpoint the issues better.

**Comment by JohnSmith-LT** [comment] 2022-07-18 10:08
No I get that @torinfo - I'll look at it again soon to see what we can do to fix the issues.

**Comment by JohnSmith-LT** [comment] 2022-07-18 10:37
I took another look @torinfo - can't see the issue in the first one that I exported (after I go back to before you reverted) and the Privacy one isn't shared in a way that I can export - if you change that that i'll pull that one down and test also...

I did notice that i'm getting a missing css file error in the ERIC one:

![image](https://user-images.githubusercontent.com/3907362/179494647-3e5fb898-8a2e-43d2-b039-299794037d4d.png)


/themes/Nottingham/undefined/undefined.css

Not sure why that is and it seems to be missing on your server and on the exported one but not in a newly created LO...

**Comment by torinfo** [comment] 2022-07-18 12:04
@JohnSmith-LT The undefined.css is caused by tyhe fact that the original theme from the client installation does not exist in xot310beta. But if you reset the theme to the standard theme, the issues are the same.

1. I renamed xot310beta to xotbeta (old URL will redirect to new name. I added co-author rights to the other LO as well.
2. I created a copy xottest.dlearning.nl (same user credentials) and reverted that back to v3.11.1 with your Glossary code

See the differences on the screenshots below. The green parts show what should be there (and is there in the reverted code). There used to be more issues, but I've changed the LO to work around some of the issues in my investigation.
![2022-07-18_13-44-52](https://user-images.githubusercontent.com/5166596/179506923-5e8c86ce-dbdb-42e8-9b56-f82b4d0bfec2.png)

![2022-07-18_13-45-35](https://user-images.githubusercontent.com/5166596/179506980-72a0e65f-7800-42c8-9aa5-1a8568f18362.png)
![2022-07-18_13-46-21](https://user-images.githubusercontent.com/5166596/179507003-060ff8bd-fdc6-4878-ba09-2c16e0d923fd.png)
![2022-07-18_13-47-43](https://user-images.githubusercontent.com/5166596/179507046-e23f8308-6d14-4dc9-ad87-05ee4f7939d4.png)
![2022-07-18_13-49-34](https://user-images.githubusercontent.com/5166596/179507074-87897da2-f180-4df8-a08e-4aea69ef6beb.png)

The last screenshot also shows that the issues have to do with glossary. I hope you have know some things to work with.

BTW, these are LO's that have a number of flaws not in the least because of the spaces in the media files! This is also the reason why it fails. But, It is very difficult to assess what happens in old LO's.

**Comment by JohnSmith-LT** [comment] 2022-07-18 14:44
Took me a while to get my head around what was happening but it seems that those particular pages seemed to just have the correct combination and amount of html and text nodes to somehow fall through the cracks in my code...

I think I have solved it though - I've jerry-rigged the new xottest site you put up so please test the two LO's there to see that they now don't drop any code or images. If you are happy then I'll push my changes to develop and you can pull down and test the others on the site.

**Comment by torinfo** [comment] 2022-07-18 14:51
Yeah I can imagine it was quite a puzzle. 

It seems to work fine now! Thanks! So, please commit to develop, I'll test again in xotbeta, and will cherry-pick into the release.

**Closed** 2022-07-18 15:36 UTC
Labels: bug

**Comment by JohnSmith-LT** [comment] 2022-07-18 15:38
That's it updated @torinfo - I took the chance to update a few things too to make it more readable and commented a few bits so we know why I did it that particular way (since I couldn't remember!)

**Comment by JohnSmith-LT** [comment] 2022-07-18 16:13
Sorry @torinfo further testing found a few issues with a xotbeta url creeping in, strange control characters and an issue with the original problem that @FayCross raised. Unfortunately there are now numerous fixes to cherry pick into the release...
