### ISSUE TITLE
Password protected project errors

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#862] opened 2019-10-04 08:12 UTC
Password protected projects are showing the login page like this:

![error](https://user-images.githubusercontent.com/8926470/66191747-ee540280-e686-11e9-9c05-cf6ae73a8060.png)

If I roll back [this commit](https://github.com/thexerteproject/xerteonlinetoolkits/commit/be87321acae768a99567ad015933ba54f8eac8eb#diff-0bdab972cc384c741ef8fa77d5bfd1f4) about workspace branding then these errors don't show & the page works as expected.

**Comment by ronm123** [comment] 2019-10-04 09:28
@FayCross I was wondering if this might have been a php version issue but I just created a quick test file on xot.xerte.org.uk and set that to password protected and sure enough that shows the same problem https://xot.xerte.org.uk/play.php?template_id=183

**Comment by ronm123** [comment] 2019-10-04 09:51
[login_library.zip](https://github.com/thexerteproject/xerteonlinetoolkits/files/3689953/login_library.zip)

@FayCross can you try the attached login_library.php and confirm if that resolves the issue?

**Comment by FayCross** [comment] 2019-10-04 09:59
Thanks Ron - yes that removes the errors but I can't check right now whether actually logging in still works (only have access to my xampp version right now)

**Comment by ronm123** [comment] 2019-10-04 10:15
Thanks @FayCross I've committed the change and hopefully @torinfo can quickly check that all is correct?

I've tested the revised file on one of my sites that was showing the same errors and the commit fixes the issue and allows login to view the LO. However this is not something I have used very often or encouraged others to use and I think we need to have a look at how this looks and works for a future release.

**Comment by torinfo** [comment] 2019-10-04 10:53
@ronm123 I could reproduce as well. I don't see your commit yet, so cannot comment yet.

**Comment by ronm123** [comment] 2019-10-04 13:35
@torinfo https://github.com/thexerteproject/xerteonlinetoolkits/commit/96bf73f3ef27f5254aff37b9b900c3c957b60d20

**Comment by torinfo** [comment] 2019-10-04 14:45
@ronm123 @FayCross COmitted alternate fix that sill loads branding.css. Otherwise braning.css would not be loaded in the normal case of login, i.e. with Db authentication

**Comment by ronm123** [comment] 2019-10-04 15:33
@torinfo I committed a tiny change to your updated file just adding a space between the password string and the input field.

I think the language string where it currently says login area should probably change unless this is used somewhere else too? If's it's only used for LOs set to password protected then perhaps the language string should change to something like:

To view this project please login.

Also the styling of this login area seems like it dates back to very early styling. If I add the following to a branding.css file it works fine:
`#playitcontainer {
    padding: 10px;
    background-color: #4D585E !important;
}
.top_left.sign_in_TL.m_b_d_2_child {
    background-color: #EDEDED !important;
}
.bottom_left.sign_in_BL.m_b_d_2_child {
    padding: 10px;
}`
But when I tried adding that to frontpage.css it didn't seem to have any effect?

**Comment by ronm123** [comment] 2019-10-04 15:38
For reference this is what it looks like now:
![image](https://user-images.githubusercontent.com/5167146/66220593-31cd6180-e6c5-11e9-89e0-0cdecee5b60c.png)
and with the additional css
![image](https://user-images.githubusercontent.com/5167146/66220708-66d9b400-e6c5-11e9-843c-6df34730f9a8.png)

**Comment by torinfo** [comment] 2019-10-04 16:04
@ronm123 I'll have a look. The function login_prompt is used for the login of password protected LO's. The function login_form is for the regular login.

**Closed** 2022-07-29 10:07 UTC
Labels: bug
