### ISSUE TITLE
RSS Template

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#33] opened 2013-10-02 13:57 UTC
THere's no HTML5 RSS template, so creating and previewing one fails. Changing the runtime to Flash and it works OK. This isn't a surprise as such, but a potential bump for users.

**Comment by JohnSmith-LT** [comment] 2015-05-27 15:48
If you try to create an RSS Feed you get errors

![image](https://cloud.githubusercontent.com/assets/3907362/7840612/2208be46-0490-11e5-9746-2965dbc326e8.png)

Feed is created in workspace but closing and reopening editor gives blank editor

![image](https://cloud.githubusercontent.com/assets/3907362/7840633/3b5591e4-0490-11e5-9ff4-b910986a286d.png)

**Comment by torinfo** [comment] 2015-05-27 15:50
I'll have a look.

**Comment by pgogy** [comment] 2015-05-27 15:53
Not modularised?

**Comment by JohnSmith-LT** [comment] 2015-05-27 16:36
Dont know what the issue is, ran out of time today but from the message it looks to be themes related...

**Comment by torinfo** [comment] 2015-05-27 18:44
That's easy to fix. The blank pages though, that's going to be a lot of work....
Bummer.

ïll try to think of something.

**Comment by JohnSmith-LT** [comment] 2015-05-27 19:23
Do you mean the blank editor panes? What do you suspect is the problem?

**Comment by torinfo** [comment] 2015-05-28 07:17
The new editor made the hardcoded assumption that the toplevel node of the data.xml was called 'learningObject'. But that's not the case for rss...

In the end it turned out to be relatively easy to refactor that.

**Comment by JohnSmith-LT** [comment] 2015-05-28 09:31
Great work!

**Comment by JohnSmith-LT** [comment] 2015-05-28 09:52
Ah, the original issue still remains. When you create an RSS template it defaults to html5 playback and tries to load from /modules/xerte/parent_templates/Rss/ path which doesn't have xenith and afaik xenith can't deal with it anyway?

**Comment by torinfo** [comment] 2015-05-28 10:13
Ok, so I first need to figure out how rss is working in Flash. 
I would be a shame to have to support the flash engine just because of rss....

**Comment by JohnSmith-LT** [comment] 2015-05-28 10:27
Are we planning to remove the flash engine from the v3 release?

**Comment by torinfo** [comment] 2015-05-28 10:30
No, so the best short-term solution is to make sure the flash engine is activated for rss projects.

**Closed** 2015-06-01 12:18 UTC
Labels: bug, high priority
