### ISSUE TITLE
Page import bug

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#651] opened 2017-07-14 14:37 UTC
I have one project in my workspace that I can't get import to work in. When I try it gets stuck with the loading spinner & doesn't load the project list. There's nothing unusual in the project as far as I can see & import works fine in all of the other projects. If I duplicate the project the copy will import pages to it ok.

I get the error 'Cannot read property 'children' of undefined' and can also see that the console.log that's being done in import-choose.js (line 196) has one less item in it than on all the pages where it works ok (it's missing info about the workspace that's normally here).

To add to the weirdness if I start to import into any other project but click the workspace icon I get a list of this misbehaving project's pages on the right (I'd assume that there shouldn't be any pages listed if you select workspace instead of a project). No matter what other project I am in, if I click workspace I always get the pages listed of this strange project:

![capture](https://user-images.githubusercontent.com/8926470/28216631-464c440a-68aa-11e7-827d-3eca9a81a461.JPG)

I think this might be something that's hard to reproduce but will leave it here in case you can!

**Comment by FayCross** [comment] 2017-07-14 14:41
I've just realised it's project no. 1 in my install - i imagine it's to do with that rather than anything in the essay above! Does it confuse project 1 with the workspace?

**Comment by torinfo** [comment] 2017-07-16 09:57
Really weird. I can reproduce this! But only on object 1!!
I will try to fix this later.

**Comment by ronm123** [comment] 2017-07-24 12:09
Hi all
Just a quick update to say that Tom and I exchanged some emails after our email discussion about this and Tom can’t replicate the issue that I still see. However I still get this on different installations/servers and although it’s not really a big issue now because it only shows pages from my own projects, not pages from projects belonging to others like Fay first reported, it seems to me that it’s still a bug and potentially uncertain given that it’s not easy to see what all users will get in a particular install. Ideally clicking a folder should never show any pages to avoid confusion.

Here’s a quick recording of what I get via my xampp copy of develop updated this morning to include the changes Tom committed on Friday  https://mitchellmedia.co.uk/import_pages_folder_selection.gif 

I have 3 folders in the workspace
Themes – click this and I see pages
Providers – click this and I see pages
Tests – click this and I don’t see any pages

In Providers I have 4 subfolders each containing projects. When I click 3 of those they show pages but the fourth doesn’t.

I get the same in my workspace on some other installations but not all.
I have no idea why its only me seeing this! Can you test on your installations and ask others to do so too?

**Comment by JohnSmith-LT** [comment] 2017-07-26 10:44
Hi @FayCross, hope you are well. Can you see whether the commits I made a few days ago fix this?

**Comment by FayCross** [comment] 2017-07-28 10:06
Sorry but no, I still have these problems with project 1

**Comment by JohnSmith-LT** [comment] 2017-07-28 10:50
Do you see any errors in the console? Any chance you can post a copy of any errors etc?

I can't see why a copy of the project would work but the original wouldn't though...

**Comment by FayCross** [comment] 2017-07-28 11:32
It's a similar issue to Ron's where pages were showing when you selected a folder that had the same id as one of your projects. This issue only happens for project number 1 though as it seems to confuse it with the workspace. Tom could recreate it with his project no. 1 - can you?

Error is 'Cannot read property 'children' of undefined'. I can kind of see what's happening but don't know where to fix it...

workspace.items array is shown in console (from 242 of import-choose.js) just before error & in all other projects the array has workspace as 1st item but in this project the workspace is missing from array and it goes straight into all the projects. I guess the array is made up of all projects except those matching the current project's id but in this case it skips workspace too as it also seems to have id 1. It needs a similar fix to that done for projects but so workspace id is ignored too.

**Comment by FayCross** [comment] 2017-07-28 11:33
& copies of project don't have this issue as they're not project no. 1

**Comment by JohnSmith-LT** [comment] 2017-07-28 11:35
Ah I get it now... let me try to fix it and i'll commit something in the next hour or so...

**Closed** 2017-07-28 12:16 UTC
Labels: bug, Editor

**Comment by JohnSmith-LT** [comment] 2017-07-28 12:17
Does that fix it?

**Comment by FayCross** [comment] 2017-07-28 12:19
Yes, thanks!
