### ISSUE TITLE
Autocolumns ckeditor plugin

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#1128] opened 2022-06-28 11:19 UTC
Hi @ronm123, @FayCross, @torinfo

Following on from the discussions at the dev day and since, I have written an "autocolumns" plugin for the editor which in my brief testing appears to work great... It adds no css to the player because it uses the autocolumnsX classes that you added for the Text page @ronm123 but it seems to work great on all the pages that i've tested so far - I remember you mentioning the tabbed pages so here is an example of a 2 and 3 column block in those pages:

![image](https://user-images.githubusercontent.com/3907362/176163810-fa7acf70-23cf-430b-81f9-ba1af7273344.png)

![image](https://user-images.githubusercontent.com/3907362/176163889-d2682825-2d6a-4fea-8ec5-c56033001b7c.png)

You can also get creative (though perhaps not artistic) by mixing them like this (here we have a 1 column, then a 2-column and then a 3-column in the same box):

![image](https://user-images.githubusercontent.com/3907362/176182588-32073100-a728-4c49-89c4-dd05876fbbcf.png)
(looks pretty good with a couple of horizontal lines thrown in as separators)

Obviously, like with your example in the text page, the columns collapse fluidly when you resize the screen. One interesting thing at present is that if you use your code @ronm123 in the Text page and also add a 2 or 3 column section then you can get even more funky layouts. Not sure if that is a step too far though (this is a Text page with 2 of your columns turned on and with a block of my 2-columns added - again, of course on small screens these collapse to single column automagically):

![image](https://user-images.githubusercontent.com/3907362/176182945-a77b8b13-93ea-4d8a-b853-3d05a77f65e4.png)

I will enable this today once @torinfo fixes the codesnippet issue and you can test but my only hesitation is that I have identified 15+ different scenarios and have only properly tested and coded for the first 7 or 8. There is real possibility of screwing up your existing code by, for example, selecting half a table and clicking the columns button - I also haven't tested extensively on Firefox or Edge (and none on Safari) so not that extensively and Firefox is known to handle selections and ranges differently so data could be lost in the process. The only good thing is that Ctrl-Z or Undo will take you back as normal but users need to be aware that data could be lost in the process...

My question now is this release (with basic testing) or next release with extensive testing and updates?

**Comment by ronm123** [comment] 2022-06-28 11:37
@JohnSmith-LT looks good from what I can see but obviously can't test until you commit. If it works and goes in this release should we move the commit I made for the plain text page? It sounds like we probably should but I'm not entirely sure how to do that! If this works without any obvious problems and in most places where the full text editor can be used then I think it will be very popular and would be keen to see it in this release rather than wait. But that's just my thoughts.

**Comment by JohnSmith-LT** [comment] 2022-06-28 11:39
Have committed now @ronm123

**Comment by JohnSmith-LT** [comment] 2022-06-28 11:46
What still needs doing:

1. Perhaps a change to the css to show differently in the editor. If you expand the editor you do get a view for how it will look but there is extra box around and shading which perhaps could be removed
2. Testing with different scenarios - I have a non-extensive list running to about 18x different uses cases (for example, what if you make a selection containing half a table, a paragraph or unstyles text and 2x blocks of already styled autocolumns? - I have no concept of how the code would work in those situations and the code at present only deals with range[0] and I know that FF can return many ranges when you cross section/widget/object boundaries like this...)

**Comment by torinfo** [comment] 2022-06-28 12:15
@JohnSmith-LT Brilliant. I agree with Ron, that it would be good to release now (evn though it might not be perfect in the situations you mention John).

**Comment by JohnSmith-LT** [comment] 2022-06-28 12:45
Ok, thanks @torinfo and @ronm123, I agree that this could be a great feature...

What I've tested so far (only really in Chrome and Edge though) and works consistently:

Each of these done before clicking the Autocolumns menu button

1. Caret in text, outside of Autocolumns (AC from now on) widget, nothing selected - **New, empty AC created on OK**
2. Some stuff selected outside of AC widget - **New AC created on OK containing selection**
3. Outside AC widget, everything selected - **New AC created on OK wrapping everything**
4. Same as above two but containing < imgs>, other widgets, etc - **New AC created on OK containing selection**
5. AC widget selected, using the handle - **Selection promoted to containing AC, settings picked up and dialog opened**
6. Caret flashing inside AC widget, nothing selected - **Selection promoted to containing AC, settings picked up and dialog opened**
7. Some text in AC widget selected (not all) - **Selection promoted to containing AC, settings picked up and dialog opened**
8. Everything inside widget selected, or < p> or lowest < div> selected in CKEditor breadcrumb - **Selection promoted to containing AC, settings picked up and dialog opened**

**Comment by ronm123** [comment] 2022-06-28 13:24
@JohnSmith-LT @torinfo sorry I think I spoke too soon :-(
Now that you've committed this I notice some issues with different page types that I also noticed when testing where I could possibly add the auto columns code that I added to the plain text page. As usual I've started with a page types demonstrator and skipped past the title page and plain text page to the bullets page. My test bullets page has a small image aligned centre in the last para. If you try this even without the image you'll see there's a problem and I guess I should have mentioned this previously e.g. I decided I couldn't make auto columns available on every page because in many pages it doesn't work or impacts how the page works.

The next page I tested was orientation which obviously has 4 text areas. My local example is the same as the one at https://xot.xerte.org.uk/play_116#orientation which has an image (round target) aligned right. Using Ctrl A or selecting and dragging and then clicking the auto columns button I can't seem to get the AC div to wrap around the image and all the text.
In this case I don't suppose that matters too much but what does matter is if I've closed the editor, viewed my project and then decided the AC doesn't work I can't easily remove it without switching to source view. Or am I missing a trick here?

I think the problem is going to be that there are other places where we will hit similar issues because it's available everywhere. Actually having it available everywhere is great but I don't know how we differentiate between pages or panes where we know it works and those where other code means it doesn't. e.g. in the orientation page we'd probably want all 4 text areas to wrap as though they were part of one single text area although likewise I can see it being useful to have a mix of columns on the same page based on what you selected as in some of Johns examples.

Perhaps we could leave this for users trial and error but I think before we could do that we'd need an option to remove any and all AC divs without breaking any existing formatting. It also does make me a bit concerned that there are so many different permutations with different page types and we want to release on Thursday so perhaps there isn't enough time to test before release?

**Comment by JohnSmith-LT** [comment] 2022-06-28 16:27
Thanks for the feedback @ronm123 and @torinfo. I've spent another hour on it and now have:

- Fixed the context menu issue - if you are inside an Autocolumns widget then the Edit/Remove Div option is greyed out. Also you can right click to open the Autocolumns dialog without using the menu button. Could do with being in it's own group but for now it works.
- Added a Remove button - now if you are editing an existing Autocolumns widget then the Remove button will prompt you and then remove the feature, retaining the content within. If you are adding a new one then the Remove button is greyed out...

I still need to pull all of the strings out into an English language file so I've added that to the checklist above but would welcome any other feedback that you or @FayCross has... I take on board what you've said @ronm123 about it not being useful in many pages but perhaps the benefits in the other pages outweighs the issues in those affected pages... I don't know but any suggestions on how to fix the issues in those pages would be welcome too...

**Comment by JohnSmith-LT** [comment] 2022-06-28 17:25
I think also the thing missing from the above discussion is that you can also use these in Bootstrap:

![image](https://user-images.githubusercontent.com/3907362/176244662-9fc7076c-7d8f-4a52-82c7-ece23e02fb5f.png)

I got this all working just by adding a styles box and putting in your autocolumns css rule @ronm123 so does that swing things in favour of "lets include it" or does that add more concerns about breaking things in Bootstrap also?

**Comment by ronm123** [comment] 2022-06-28 17:41
@JohnSmith-LT I didn't test in Bootstrap yet but can't really see any likely issues with Bootstrap. I think as long as it's easy enough for people to try it and then remove it without having to go into to source view or to have to rely on undo then definitely worth including. As I mentioned though if we include it we should probably remove what I added just for the plain text page and I'm not sure how to do that efficiently?

**Comment by ronm123** [comment] 2022-06-28 17:42
BTW plan to test a bit more in the morning and also add the XOT header colour option that I asked about via email but nobody objected.

**Comment by JohnSmith-LT** [comment] 2022-06-28 18:56
Ok, no worries. I will be working on the English language file tonight so any suggested changes to the Names, Labels, Titles, Alt text or Popups would be greatly appreciated...

To remove what you added for the Text page then all you need to do is remove the XML from the page structure and then rebuild the .xwd files but leave the CSS. The CSS then needs to be added to the correct place in Bootstrap (and possibly the Decision Tree model) and then the classes and styles that the editor adds will just work.

**Comment by ronm123** [comment] 2022-06-29 13:11
@JohnSmith-LT @FayCross @torinfo just picking up on this now... I think we've decided to include this so the wizard option I added for plain text should be removed. Is that correct?

I can easily remove the options from the plain text page wizard and leave the css in place as John suggests. I'd previously added those styles to desktopstyles is that correct? https://github.com/thexerteproject/xerteonlinetoolkits/commit/07271b543aff9565b0b51f5c6f8843add59cfe04#diff-631df2df4ce62ff7edbc50d65619194a4dd65e98a9e83a6066561986abef25f1

not sure why I left the default ruler in autocolumns3 commented out but will uncomment because it's changed by the options anyway.

I'll test adding the same styles to bootstrap and decision.

We then need to update the release notes too.

**Comment by ronm123** [comment] 2022-06-29 13:31
@JohnSmith-LT @FayCross @torinfo I've committed these changes now e.g. removed the plain text page optional properties and added the default autocolumn styles to bootstrap and decision. Have also tested in both those projects that the basic functionality works.

**Comment by ronm123** [comment] 2022-06-29 14:00
@JohnSmith-LT yes it's a great option and much better than limited to just the plain text page! I'll have a go at the release notes for this if you wish? I need to remove what I added for the plain text page anyway but will be a lot easier to be able to demonstrate it working once the xot.xerte.org.uk install has been upgraded.

**Comment by JohnSmith-LT** [comment] 2022-06-29 14:04
Yes please @ronm123. You know the audience better than me and always do a great job getting the wording spot on. Remember to let me know if you think any of the wording for the buttons/titles/prompts etc need changing and i'll do that before tomorrow.

**Comment by FayCross** [comment] 2022-06-29 21:59
@JohnSmith-LT I've only tested in Bootstrap template so far but have a couple of comments.

I've written two paragraphs, selected them and clicked the column button to turn them into 2 columns - this works well. If I click the column button again to edit the columns, don't make any changes and click cancel, the dialog closes and my text no longer appears in columns. My last paragraph is also duplicated and appears above the first one (so before I edited column it showed p1 - p2 and after editing I see p2 - p1 - p2). If I move away from the page and back to it the text is showing as it should be (2 columns with 2 paragraphs).

Should there be a comment in the dialog box mentioning that this is the max no. of columns and the amount shown depends on the screen size? I thought it wasn't working initially when I changed from 2 columns to 3 in the editor as the text stayed in 2 columns. It wasn't until I previewed and saw that there were 3 columns that I realised that it's because the text field in the editor is reasonably small so didn't want to show more than 2 columns.

The spacing between columns shouldn't be 0 by default as I think most people will want some spacing added.

**Comment by JohnSmith-LT** [comment] 2022-06-29 22:38
Is this in Firefox @FayCross ? Do you see the same if you use Chrome? I haven't tested a great deal in Firefox in recent days so it may be that changes that I have made to fix one thing have broken it in Firefox. I read that Firefox definitely handles selection and ranges differently - I will look at that in the morning but I suppose if that is a deal breaker then should we either remove this until later release or add to the notes that it doesn't work correctly in FF. What do you think @ronm123 @torinfo

**Comment by FayCross** [comment] 2022-06-29 22:41
@JohnSmith-LT chrome. It has never made me lose content - just duplicates some of it occasionally!

**Comment by JohnSmith-LT** [comment] 2022-06-30 01:37
Thanks @FayCross . I've made the defaults for spacing and line thickness 1 and 1 but if you think they should be different then it's easy to change this, just let me know.

I also think I've fixed the strange extra paragraph bug. I couldn't reproduce the bug where you click cancel and the box goes away though - can you still reproduce that and if so can you provide steps to reproduce and I'll take a look...

**Comment by ronm123** [comment] 2022-06-30 08:21
@FayCross @JohnSmith-LT in the wizard for the plain text page (now removed) I had added the following tips and tweaked them below to remove reference to plain text:

If you have long paragraphs of text then your page or selection may look better displayed as columns rather than long lines, especially on higher resolution displays. Use this editor option to select blocks of text and enable/disable automatic responsive columns for that selection. Use the additional options to control how many columns and ruler style etc.

Note: the number of columns option represents the maximum number of columns you require but depending on device/screen resolution may display fewer columns if the number chosen will not fit. e.g. 5 may become 4 and then reduce further as resolution or window size is reduced.

Automatic columns do not provide precise control over exactly where your content wraps so may not be suitable in all cases. Alternatively in XOT use the multi-navigator page where in column mode you can manually control the number of columns. As an alternative in Bootstrap you could use html to add and manually control columns but that does require adding classes/code in source view.

We can include this in the release notes (and the wiki I guess) but I don't know if there is a more 'on demand' way to display this? Or indeed any changes/additions needed?

**Comment by FayCross** [comment] 2022-06-30 08:30
@ronm123 @JohnSmith-LT I think this text would be useful to include in the column dialog:

Note: the number of columns option represents the maximum number of columns you require but depending on device/screen resolution may display fewer columns if the number chosen will not fit.

**Comment by JohnSmith-LT** [comment] 2022-06-30 08:36
Something like this @ronm123 @FayCross 

![image](https://user-images.githubusercontent.com/3907362/176632187-21f36f0e-d7d1-4463-addf-ffc19c204a39.png)

**Comment by FayCross** [comment] 2022-06-30 08:42
Yes, although it could possibly be shorter: 'Note: this is the maximum number of columns. Fewer columns will be displayed if device/screen resolution means this number will not fit.' I don't mind much though!

**Comment by JohnSmith-LT** [comment] 2022-06-30 08:46
Ok lets go with that @FayCross although now it sounds like it should be written in this format: Objects in the Rear View Mirror May Appear Closer Than They Are

Columns in the final LO view may appear fewer than they are...

**Comment by ronm123** [comment] 2022-06-30 08:52
Hmmm perhaps we should also say something like:

Objects in the small rear view mirror will not display the same when on the open road...

Even with columns set to 3, 4 or 5 you may not see more than 2 columns in the small editor window and may need to play your project to see 3 or more columns.

**Comment by ronm123** [comment] 2022-06-30 09:02
Not mentioning the following because it's a real problem but in case it's relevant in any way John I've just been testing with my local copy of the XOT page types demonstrator and noticed the following:
On the plain text page I have the a mix of styles and when looking at the source view it ends with:
`<blockquote class="bq2">
  <p>We&#39;ve used a few different styles here to show some of the possibilities but the page is arguably already a bit distracting as a result. You should use the wide mix of styles available sparingly and be careful to ensure that your text pages are easy to read and not too &#39;noisy&#39; with lots of unnecessary styles!
  </p>
</blockquote>`
and looks like this:
![image](https://user-images.githubusercontent.com/5167146/176636686-c77c3945-f921-46c8-ae13-aed67b849dab.png)
If I select all and add 2 auto columns I end up with this:
![image](https://user-images.githubusercontent.com/5167146/176636864-9a6368ee-a688-4930-a4ea-b42ba1d9c8c8.png)
However if I remove the auto columns and first add a para after the blockquote and then select all I don't get that extra empty blockquote:
![image](https://user-images.githubusercontent.com/5167146/176637210-3988a8b6-4e24-4181-a187-7225a66a6aaf.png)

Obviously that last para could just be `<p>&nbsp</p>` and pehaps this is an unusual example and in most cases will not occur but just sharing for reference.

**Comment by ronm123** [comment] 2022-06-30 09:06
![image](https://user-images.githubusercontent.com/5167146/176638246-95757aed-013a-4c17-b1fe-3d4cb3518c9d.png)

![image](https://user-images.githubusercontent.com/5167146/176638302-4baaaa2c-6c3b-4337-b46d-dc9df834df6f.png)

![image](https://user-images.githubusercontent.com/5167146/176638395-aa622b29-9125-4f27-8040-e4203e213f3e.png)

**Comment by JohnSmith-LT** [comment] 2022-06-30 09:12
Yes @ronm123 I think my selection routine is still rather naïve and definitely improved upon - in some cases i've erred on the side of caution and put in more than perhaps I need to for fear of losing content and then the author can tidy up. I will work on this though when I get back from holiday and try to get a better version into the download - hopefully not many people are rushing to download on day 1 of the release...

If you find any more of these oddities though then do please capture screenshots and post here as it gives my extra information and scenarios to work with...

**Comment by ronm123** [comment] 2022-06-30 09:33
@JohnSmith-LT it's still great to have this as it is now even with a few small issues as long as no content is lost when undoing/removing etc. The only other issue I've found so far and already mentioned is where I have a para of text with an image aligned right. Doing a Ctrl + A or trying to drag to select all loses selection of the image as soon as I move to select the auto columns button. However it works if I select body at the bottom of the window. I'll add a tip about this in the release notes e.g. if you wish to select everything in a text box select the body tag bottom left of the editor window and then click the auto columns button.
![image_and_text_selection](https://user-images.githubusercontent.com/5167146/176643986-536fb3c2-8425-453a-8eca-2a5b0a11897f.gif)

**Comment by JohnSmith-LT** [comment] 2022-06-30 10:20
Have you tried right-clicking on the selection @ronm123

**Comment by ronm123** [comment] 2022-06-30 10:37
@JohnSmith-LT I think it's some kind of focus issue and right clicking loses the selection too. But I think it's fine adding some guidance in the release notes about using the selectors at the bottom of the editor window - that's quicker and more reliable if you want to select everything.

**Comment by JohnSmith-LT** [comment] 2022-06-30 11:24
Hi @ronm123 it would appear that that issue that you've found isn't even related to the columns plugin. You see below, if I remove both the columns and recorder plugins and then click at the end of the editor and press Ctrl-A then it briefly selects everything and then a second later it unselect it...

So this is either a new 'feature' or one that has perhaps been around for a long time and we've just never noticed before...

![StrangeUnselectIssue](https://user-images.githubusercontent.com/3907362/176665566-0b62010f-26d5-461e-843f-234d7604fb3f.gif)

**Comment by FayCross** [comment] 2022-06-30 12:32
@JohnSmith-LT I'm getting errors in editor since your last commit. Line 85 of plugin.js

**Comment by JohnSmith-LT** [comment] 2022-06-30 12:50
Hmm... is it caching @FayCross ? I'm not seeing any errors -have you pulled down the latest commits?

**Comment by FayCross** [comment] 2022-06-30 12:59
@JohnSmith-LT was the last commit supposed to include a language file?

**Comment by ronm123** [comment] 2022-06-30 13:00
@JohnSmith-LT it's not caching I'm getting errors too. Was just testing the banner stuff in Bootstrap and noticed that if I try to go to a text area the console shows the following error:
http://127.0.0.1/develop/editor/js/vendor/ckeditor/plugins/xotcolumns/lang/en.js?t=J5S8 net::ERR_ABORTED 404 (Not Found) 105
and Uncaught TypeError: Cannot read properties of undefined (reading 'toolbarButtonLabel') plugin.js 3558:85
and the text area doesn't display in the wizard.

**Comment by ronm123** [comment] 2022-06-30 14:17
@JohnSmith-LT is the button/icon you've used for autocolumns and FA icon? If so what is it?
I know some of the newer icons don't show under our search but can be used if you grab the code from elsewhere but I couldn't find one that exactly matched the one you've used - perhaps it's not FA?  At the moment I've added a new 'Editor enhancements' section to the release notes with placeholder tabs for each new feature. The fact that the icon doesn't exactly match probably doesn't matter because it can be seen in the screenshot anyway?
![image](https://user-images.githubusercontent.com/5167146/176700624-a9dfb175-21fa-44db-a231-a3a7ab22edfb.png)

**Comment by JohnSmith-LT** [comment] 2022-06-30 14:27
I think it started out as this @ronm123 https://fontawesome.com/icons/columns-3?s=solid but I resized it and stretched it since I wanted it more square... I can change though if you think it would be better to...

**Comment by ronm123** [comment] 2022-06-30 14:46
@JohnSmith-LT I think that's fine as it is. But likewise I think that button is newer than we currently load into projects so I'll leave the button I've used in the navigator heading for now - I doubt anyone will notice the difference!

**Closed** 2022-07-28 08:13 UTC
Labels: New feature, Needs testing
