### ISSUE TITLE
new banner option in Bootstrap

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1129] opened 2022-06-28 13:54 UTC
@torinfo I've just been testing the new banner option you've added to Bootstrap so a few comments/questions...

I noticed that you named the options smaller banner and Jumbotron. I'm not sure we should refer to Jumbotron. Although that makes sense to us I think for the everyday user that will not mean anything and in fact I did a search and the common definition seems to be as follows:
A jumbotron indicates a big box for calling extra attention to some special content or information. A jumbotron is displayed as a grey box with rounded corners.
Also in Bootstrap 5 apparently the jumbotron component is removed in favour of utility classes like .bg-light for the background color and .p-* classes to control padding.

Also smaller banner is perhaps confusing and make people think that means smaller than they are used to previously. I wonder if Fixed height banner (default) and Full screen banner would be better labels for this. In fact perhaps Large banner for the second option if there was an option to control height too. (see below)

Also I think there should be an option to set the height of the header so that it isn't only full screen. e.g. could be half-height or quarter height or just expand with it's contents. At the moment it makes more sense when there is an image attached and to show that full screen but without an image I'm not sure it works full screen.

I know with some examples of this via custom code there is a flashing prompt bottom centre of the large header and also when scrolling back it collapses to the smaller height. It would be good to add those as optional properties too (especially the collapsing option) but I guess that can weight until a future release.

**Comment by ronm123** [comment] 2022-06-28 14:09
Sorry I meant to add that ideally this should also include text alignment options for both vertical and horizontal alignment similar to what we have in the XOT title page. e.g. I just tested with a background image and long title and subtitle. This would look great especially with the page link optional property to use a short title for the navigation but a long title in the page. But in the screenshot below you can see that ideally you would want vertical control over the text and it's only as low as it is because of the logo.
![image](https://user-images.githubusercontent.com/5167146/176199500-e89a41f1-f85b-41fc-ac25-7e92d5fae0e5.png)
I think there's also a change in the font size of the subtitle when in the large banner vs the small banner unless that's just an illusion.
There's also a debugger line in there somewhere.

**Comment by ronm123** [comment] 2022-06-28 14:51
@torinfo just tested the variable height option and using vh works e.g.
`.scale {
    height: 75vh;
}`
or
`.scale {
    height: 95vh !important;
}`
also makes it more obvious that there is something to scroll down to.
Let me know what you think about all the comments here and if helpful I could have a look tomorrow at at least adding height options as an optional property.

**Comment by torinfo** [comment] 2022-06-29 09:17
@ronm123 Working on this. All good points!

**Comment by torinfo** [comment] 2022-06-29 10:14
@ronm123 
- Named the options Full screen , Fixed height
- You specify the fixed height (with a stepper at the moment, but we can change that to vh if you want
- You can specify whether to collapse the full screen banner (default = true)
- You can specify whether to show the bouncing error (default = true). The text shown comes from engine_en-GB.xml

**Comment by ronm123** [comment] 2022-06-29 12:03
@torinfo good to have the additional options.
But I think we're thinking slightly differently..
For the full screen option I was thinking it would be useful if the height didn't have to be 100% and could be perhaps 95%. Now percentage wouldn't work but vh does. The step could indicate a range between say 30%-100% with the default being 100% but in the code that's actually 30vh-100vh.
The fixed height would just be what we've always had without an option to change that.
At the very least the options you currently have need to go above 500 so it might sort of work by changing that stepper to 30vh-100vh but the collapsed height shouldn't be that value.

**Comment by torinfo** [comment] 2022-06-29 13:33
@ronm123 Can we have a look at this again after the release? 

I do not like the defaults of the header options (left aligned, repeat). I would rather have center, no-repeat

Anyway, I have not changed that at the moment. I did add an option to be able to set the background-size (auto, contain, cover)

**Comment by ronm123** [comment] 2022-06-29 14:18
@torinfo there's a bug we need to fix too although it's kind of fun! ;-)
I have a test project with multiple page to test the different options and the first two pages are full screen images with the scroll down info enabled. If I switch back and forth between those pages using the nav bar and without scrolling down then the number of flashing down arrows doubles which as I say looks quite fun as though it's shouting "you haven't scrolled down yet!" but we should probably stop this from happening.
![image](https://user-images.githubusercontent.com/5167146/176459476-8b764b06-c22c-401c-acd2-d1fecc65d9c3.png)

**Comment by ronm123** [comment] 2022-06-29 14:25
I think a related issue is that the scroll info doesn't always disappear after scrolling down or changing page.

**Comment by torinfo** [comment] 2022-06-29 15:04
I'll have a look at the Scroll down info

With respect to mobile devieces. It's basically the same as it used to be. Right?

And vertical allignment. See if you can add that. Plan to release later on the day (probably 5 minutes to 12)

**Comment by ronm123** [comment] 2022-06-29 15:45
Not quite the same as we had before because now we have a height option defined in pixels? Do you mind if I have a look at changing that to vh and with a minimum and maximum? 
Yes I think the vertical alignment should be easy enough to add.
Do you mean 12midnight or 12noon? ;-)

**Comment by torinfo** [comment] 2022-06-29 18:32
@ronm123 I cannot replicate the issue with the info twice and/or not dissapearing.

**Comment by ronm123** [comment] 2022-06-29 19:20
@torinfo I can't reliably replicate it not disappearing now but I can replicate it appearing more than once see the following:
![flashing_arrows](https://user-images.githubusercontent.com/5167146/176518593-e876ae68-0936-4fbf-8a85-943518e419ff.gif)

also I've been testing the vertical alignment of the titles but it's another one of those where I can't work out how to enable/disable the css correctly. It gets complicated because there is code that already changes horizontal alignment of the titles base on whether there is a right logo or not. The easiest way would be to provide an optional property that sets the top-margin of .titles e.g. 30% but then removes that margin when collapse kicks in. e.g. at full screen
`$(".titles").css("margin-top", "20%");` where 20% is actually the value set as an optional property from say 2% - 60%
I can get that to work but don't know how to reset that margin when scrolling back up and therefore collapsing the header.

**Comment by torinfo** [comment] 2022-06-29 20:14
@ronm123 I fixed the double arrows... :-)

The setting/disabling of the header is in a function x_CheckBanner(). Ther you should be able to add/remove the margin-top.

Just below the function is a windows.scroll function that handels the collapsing of the full-screen banner.

If you want, I can have a look at that if you commit your code, and tell me where you added the margin.

**Comment by ronm123** [comment] 2022-06-29 20:40
@torinfo I'm shutting down for the night now but yes if you can get it to work or advise where to put it I'll have another go in the morning. I tried two options just below $(".jumbotron").addClass("x_scale"); around line 1428:
Just setting the margin value but in reality the 20% would come from an optional property ranging from say 2% - 60%.
$(".titles").css("margin-top", "20%");
Or 
$(".jumbotron .titles").addClass("marginTop");
and then setting a default value for that class but also changing it when the optional property is changed.
I didn't go as far as adding the optional property but both those methods worked for moving the titles to a more suitable vertical position but I couldn't work out where or how to change back upon collapse.

BTW if we are close to finishing the release in the morning could you temporarily upgrade xot.xerte to develop so we can add some of the new features to the release notes and then after release upgrade to 3.11 instead?

Also sorry to ask again but did you see my question about the accessibility plugin?

**Comment by FayCross** [comment] 2022-06-29 20:49
@torinfo There's a bug that I think is probably related to your changes for this, although it's affecting projects where there is no banner added too. If the page title is long then the header stops expanding and you lose some of the title or subtitle:
![bs_banner](https://user-images.githubusercontent.com/8926470/176542076-323b883f-277b-4cc6-8f0f-44c93d5e3284.PNG)

**Comment by FayCross** [comment] 2022-06-29 21:20
@torinfo a couple of other bugs / comments:

- [ ] when collapse banner is off and you scroll down, the scroll down info and arrows don't disappear but stay at the bottom of the page - overlapping the page text
- [ ] when collapse banner is off and you scroll down, the section menu first appears below the banner but then jumps up to overlap it as you scroll further down
- [ ] when banner is full screen and collapse banner is on, if the banner height is larger than the full screen height things look a bit odd as you scroll down (as banner height gets bigger, not smaller)
- [ ] when banner is full screen and collapse banner is off, the banner height property could be hidden as I don't think this is used
- [ ] is the scroll down info supposed to do something when you click it? Cursor when hovering suggests it should but nothing happens. Would be good to scroll down either to banner height (if banner is full screen) or top of page contents (if banner height is fixed height)
- [ ] scroll down info and arrows appear when page first loads and disappear when you scroll down (as expected). The text and arrows don't reappear again if you scroll up again though so the banner is full screen again. Maybe they don't have to?

Like @ronm123 I'm not sure that the banner height works in the right way. I'm not sure it's ever useful to have a fixed height in pixels as this can mean it's not big enough for title text (I think that's what's happening with first bug I mentioned in comment above). I think it would work better to have the full screen option and a % of screen option (which takes up more space than the requested % if the titles don't fit in the available space).

When full screen and collapse banner is on, I would prefer the banner to shrink to the smallest height necessary to show the title text. I don't really see the value in specifying a taller height than this but this is probably just personal preference.

**Comment by torinfo** [comment] 2022-06-29 22:00
@FayCross Thank you for this. Will have a look. The issue is that when you have full screen banner, and then collapse it, the image still needs to make sense. So collapsing it to only the height needed for the titles, does not always work... I'll see what I can do.

**Comment by torinfo** [comment] 2022-06-30 09:49
@ronm123 I suppose you mean the transition in the custom code?

**Comment by torinfo** [comment] 2022-06-30 12:32
@FayCross @ronm123 I fixed/changed a lot of the issues I think.

Many more conditionals. You can choose wther you really want to set a height when using fixed height header of collapse (default is off). You only do this if the image requires it for some reason. Also height is set in vh.

Top margin can be set in %, default is 20%

I'll commit this, so you can have a look.

@ronm123 I'm going to look into horizontol title position and transitions

**Comment by torinfo** [comment] 2022-06-30 14:48
@ronm123 @FayCross Added transision
Also added title alignment for title (not only for fullscreen).

**Comment by ronm123** [comment] 2022-06-30 21:00
@torinfo @FayCross I'll mention this now but plan to revisit in the morning... The issue I noticed is that having added the hidden copy of the homepage set to use a full screen image with title left aligned and towards the middle of the page that all works great e.g.
![image](https://user-images.githubusercontent.com/5167146/176777042-28ba8351-2a69-4a94-9044-e4e4f0b7e6e7.png)
However when I then navigate to one of the other pages the titles in the standard header are lo longer centred and are overlapping the xerte logo on the left:
![image](https://user-images.githubusercontent.com/5167146/176777332-fd88d42f-4487-4d4a-be7e-1208fba33bba.png)
It seems like the css for the full screen titles is also impacting the titles when collapsed on all pages.
Speak tomorrow...

**Comment by ronm123** [comment] 2022-07-01 14:35
@FayCross @torinfo I've just hidden the apereo logo on the full screen page with css for now. I guess in future any option on individual pages to hide the logo would need to hide it in the full screen view but not in the collapsed view or have the option of both. At the moment we have the options to hide left and or right logos project wide but not on individual pages - apart from using css.

**Comment by FayCross** [comment] 2022-07-06 08:26
@torinfo @ronm123 If a page has a full screen banner then it's tricky to access the page menu using keyboard only. Try on the release notes: https://xot.xerte.org.uk/play.php?template_id=81#home - if you tab then you get stuck going between the what's new in 3.11 link and the skip of main contents link. You can only access the page links by using the down arrow to first scroll down and then tabbing

**Comment by ronm123** [comment] 2022-07-06 08:44
@FayCross @torinfo I've got a meeting starting in a minute so can't investigate further at the moment but I quickly tested and noticed another odd issue - if you follow a link to one of the version page and then hit return on the skip to main contents link it goes to the next page rather than the main contents of the current page.

**Comment by FayCross** [comment] 2024-10-18 16:04
Closing - outstanding issues are listed in new issue https://github.com/thexerteproject/xerteonlinetoolkits/issues/1337 as this one is too cluttered to easily see what needs doing

**Closed by FayCross** 2024-10-18 16:04 UTC
Labels: enhancement, question, New feature, Bootstrap template
